Repository ramsunvtech/trello-app-clone-spring-ng, pull requests merged in 2020-08, with the labels that each got.

#7 tech(base): #1 - Base Spring Boot SetUp
  services/.gitignore
  services/.mvn/wrapper/MavenWrapperDownloader.java
  services/.mvn/wrapper/maven-wrapper.jar
  services/.mvn/wrapper/maven-wrapper.properties
  services/mvnw
  services/mvnw.cmd
  services/pom.xml
  services/src/main/java/io/trello/trelloapp/DemoApplication.java
  services/src/main/resources/application.properties
  services/src/test/java/io/trello/trelloapp/DemoApplicationTests.java
Labels: enhancement

#12 feat(api/board): #8 - Add Board List API
  services/src/main/java/io/trello/trelloapp/board/BoardController.java
  services/src/main/java/io/trello/trelloapp/board/BoardListModel.java
  services/src/main/java/io/trello/trelloapp/board/BoardModel.java
Labels: enhancement

#15 feat(components/header): #3 - Add Header Component
  .gitignore
  .vscode/settings.json
  CONTRIBUTING.md
  web/package.json
  web/src/app/app.component.html
  web/src/app/app.component.spec.ts
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/app/components/app-header/app-header.css
  web/src/app/components/app-header/app-header.html
  web/src/app/components/app-header/app-header.interface.ts
  web/src/app/components/app-header/app-header.spec.ts
  web/src/app/components/app-header/app-header.ts
  web/src/app/components/app-header/index.ts
  web/src/app/components/index.ts
  web/src/assets/images/blue-mountains.jpg
  web/src/styles.css
Labels: Needs Review, New Feature

#14 feat(store): #13 - Basic ngrx store setup
  web/angular.json
  web/package-lock.json
  web/package.json
  web/src/app/app.component.html
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/common/models/board.ts
  web/src/common/models/index.ts
  web/src/store/actions/board.action.ts
  web/src/store/index.ts
  web/src/store/reducers/board.reducer.ts
  web/src/store/reducers/index.ts
  web/src/store/selectors/board.selector.ts
Labels: Needs Review, New Feature

#17 feat(api/board): #16- Add Card List API
  services/src/main/java/io/trello/trelloapp/card/CardController.java
  services/src/main/java/io/trello/trelloapp/card/CardListModel.java
  services/src/main/java/io/trello/trelloapp/card/CardModel.java
Labels: Needs Review, New Feature

#20 feat(components): #25 - Adds board list component
  web/src/app/app.component.html
  web/src/app/app.module.ts
  web/src/app/components/app-board-list/app-board-list.component.css
  web/src/app/components/app-board-list/app-board-list.component.html
  web/src/app/components/app-board-list/app-board-list.component.spec.ts
  web/src/app/components/app-board-list/app-board-list.component.ts
  web/src/app/components/app-board-list/app-board-list.interface.ts
  web/src/app/components/app-board-list/index.ts
  web/src/app/components/index.ts
  web/src/common/models/index.ts
  web/src/store/actions/index.ts
  web/src/store/reducers/board.reducer.ts
  web/src/store/reducers/index.ts
  web/src/store/selectors/board.selector.ts
  web/src/store/selectors/index.ts
Labels: Needs Review, New Feature

#27 feat(api/newCard): #22 - Add POST New Card API
  services/src/main/java/io/trello/trelloapp/card/CardController.java
Labels: Needs Review, New Feature

#28 feat(api/editCard): #24 - Edit POST Card API
  services/src/main/java/io/trello/trelloapp/card/CardController.java
Labels: Needs Review, New Feature

#31 feat(api/annotations): #30 - Add Swagger Annotations with Rename Base…
  services/pom.xml
  services/src/main/java/io/trello/trelloapp/SwaggerConfig.java
  services/src/main/java/io/trello/trelloapp/TrelloCloneApp.java
  services/src/main/resources/application.properties
  services/src/test/java/io/trello/trelloapp/TrelloCloneAppTests.java
Labels: Needs Review, New Feature

#32 feat(component/app-board-form): #10 - Adds new component board form
  web/src/app/app.module.ts
  web/src/app/components/app-board-form/app-board-form.component.html
  web/src/app/components/app-board-form/app-board-form.component.ts
  web/src/app/components/app-board-form/index.ts
  web/src/app/components/app-board-list/app-board-list.component.html
  web/src/app/components/index.ts
Labels: Needs Review, New Feature

#35 feat(api/board): #26 - Add New Board API - POST - /api/new-board
  notes.txt
  services/src/main/java/io/trello/trelloapp/board/BoardController.java
  services/src/main/java/io/trello/trelloapp/board/BoardListModel.java
  services/src/main/java/io/trello/trelloapp/board/BoardListResponse.java
  services/src/main/java/io/trello/trelloapp/board/BoardModel.java
  services/src/main/java/io/trello/trelloapp/board/BoardRepository.java
Labels: Needs Review, New Feature

#36 fix(api/card): #16 - Add JPA to Card List and Add New Card, Delete Card API
  services/src/main/java/io/trello/trelloapp/card/CardController.java
  services/src/main/java/io/trello/trelloapp/card/CardListModel.java
  services/src/main/java/io/trello/trelloapp/card/CardListResponse.java
  services/src/main/java/io/trello/trelloapp/card/CardModel.java
  services/src/main/java/io/trello/trelloapp/card/CardRepository.java
Labels: Needs Review, New Feature

#38 fix(api/h2-db): #9 - Update Card and Board Model with @Column@En…
  services/src/main/java/io/trello/trelloapp/board/BoardModel.java
  services/src/main/java/io/trello/trelloapp/card/CardModel.java
  services/src/main/resources/data.sql
Labels: Needs Review, New Feature

#37 feat(component/card): #34 - Adds card component
  web/src/app/app.module.ts
  web/src/app/components/app-board/app-board.component.html
  web/src/app/components/app-card/app-card.component.html
  web/src/app/components/app-card/app-card.component.ts
  web/src/app/components/app-card/app-card.interface.ts
  web/src/app/components/app-card/index.ts
  web/src/app/components/index.ts
  web/src/common/models/card.ts
  web/src/common/models/index.ts
Labels: Needs Review, New Feature

#40 feat(services/board): #21 - Adds board services fetch and add boards
  web/package-lock.json
  web/package.json
  web/src/app/app.module.ts
  web/src/app/board.service.spec.ts
  web/src/app/board.service.ts
  web/src/app/components/app-board-form/app-board-form.component.ts
  web/src/app/components/app-board-list/app-board-list.component.ts
  web/src/environments/environment.ts
  web/src/store/actions/board.action.ts
  web/src/store/effects/board.effect.ts
  web/src/store/effects/index.ts
  web/src/store/reducers/board.reducer.ts
Labels: New Feature

#42 feat(general/cors): #41 - Adds cors config to allow api access
  services/mvnw
  services/src/main/java/io/trello/trelloapp/TrelloCloneApp.java
  services/src/main/resources/application.properties
Labels: New Feature

#53 feat(add new card): #52 - Adds feature to get and add new cards
  web/src/app/app.module.ts
  web/src/app/board.service.spec.ts
  web/src/app/board.service.ts
  web/src/app/components/app-board-list/app-board-list.component.ts
  web/src/app/components/app-board/app-board.component.html
  web/src/app/components/app-board/app-board.component.ts
  web/src/app/components/app-board/app-board.interface.ts
  web/src/app/components/app-card-form/app-card-form.component.ts
  web/src/app/components/app-card/app-card.component.ts
  web/src/store/actions/card.action.ts
  web/src/store/actions/index.ts
  web/src/store/effects/board.effect.ts
  web/src/store/effects/card.effect.ts
  web/src/store/effects/index.ts
  web/src/store/reducers/card.reducer.ts
  web/src/store/reducers/index.ts
  web/src/store/selectors/card.selector.ts
  web/src/store/selectors/index.ts
Labels: Needs Review, New Feature

#54 feat(service/delete-card-feature): #46 - Adds delete card feature
  web/src/app/components/app-card/app-card.component.ts
  web/src/store/actions/card.action.ts
  web/src/store/effects/card.effect.ts
  web/src/store/reducers/card.reducer.ts
Labels: Needs Review, New Feature

#55 feat(service/edit-card): #48 - Adds edit card service
  web/src/app/components/app-card/app-card.component.html
  web/src/app/components/app-card/app-card.component.ts
  web/src/app/services/card.service.ts
  web/src/store/actions/card.action.ts
  web/src/store/effects/card.effect.ts
  web/src/store/reducers/card.reducer.ts
Labels: Needs Review, New Feature
